# Build pipeline for Fantasy Football Team Builder 

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    python -m pip install pylint
    pylint get_player_game_stats.py --disable=all --enable=F,E,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode
  displayName: 'Run lint tests'  

- script: |
    pip install pytest
    pytest ./ --junitxml=junit/test-results.xml
  displayName: 'Test with pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python'

- script: |
    tar -zcvf $(Build.ArtifactStagingDirectory))/ffb_draft_picker.tar.gz ./read_player_csv.py ./requirements.txt ./data/*

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: FFB_Draft_Picker 
